### Q1. What is data encoding? How is it useful in data science?

In [ ]:
data encoding simple meaning is to convert categorical value feature into the numeric value feature.
it is very use full beacuse our ml models wrok on a numeric data. so if we build a ml model which prfrom mathimatic 
oprations so if we convert categorical to numeric then this feature can be use, other wise we have to pass only numeric 
feature.

### Q2. What is nominal encoding? Provide an example of how you would use it in a real-world scenario.

In [ ]:
Nominal encoding:
    Nominal encoding, also known as categorical encoding, is a data encoding technique.
    In nominal encoding, each category is assigned a unique integer or we can say binary value, but there is no meaningful 
    relationship or ordering between the assigned values. 
    This encoding is typically used when there is no ordinal relationship between categories,
    and they are simply different groups without any natural ordering.

One of the most common methods of nominal encoding is one-hot encoding, 
where each category is represented as a binary vector. 
Each binary column corresponds to a category, and a 1 is placed in the column representing the category to which a data 
point belongs, while all other entries in that column are set to 0.

In [18]:
import pandas as pd
import seaborn as sns 
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()

In [5]:
df = sns.load_dataset("iris")
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [9]:
df["species"].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [10]:
o = one.fit_transform(df[["species"]])

In [13]:
one.get_feature_names_out()

array(['species_setosa', 'species_versicolor', 'species_virginica'],
      dtype=object)

In [14]:
new_iris = pd.concat([df,pd.DataFrame(o.toarray(),columns=one.get_feature_names_out())],axis=1)

In [15]:
new_iris

sepal_length  sepal_width  petal_length  petal_width    species  \
0             5.1          3.5           1.4          0.2     setosa   
1             4.9          3.0           1.4          0.2     setosa   
2             4.7          3.2           1.3          0.2     setosa   
3             4.6          3.1           1.5          0.2     setosa   
4             5.0          3.6           1.4          0.2     setosa   
..            ...          ...           ...          ...        ...   
145           6.7          3.0           5.2          2.3  virginica   
146           6.3          2.5           5.0          1.9  virginica   
147           6.5          3.0           5.2          2.0  virginica   
148           6.2          3.4           5.4          2.3  virginica   
149           5.9          3.0           5.1          1.8  virginica   

     species_setosa  species_versicolor  species_virginica  
0               1.0                 0.0                0.0  
1               1.0                 0.0                0.0  
2               1.0                 0.0                0.0  
3               1.0                 0.0                0.0  
4               1.0                 0.0                0.0  
..              ...                 ...                ...  
145             0.0                 0.0                1.0  
146             0.0                 0.0                1.0  
147             0.0                 0.0                1.0  
148             0.0                 0.0                1.0  
149             0.0                 0.0                1.0  

[150 rows x 8 columns]

### Q3. In what situations is nominal encoding preferred over one-hot encoding? Provide a practical example.

In [ ]:
when we want to encode data with some specific order. when we have small number of categories in our feature then we can
also use nominal encoding.

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [3]:
df=pd.DataFrame({"keys1":["first","sec","thr","four","five"]})
df

keys1
0  first
1    sec
2    thr
3   four
4   five

In [5]:
temp = encoder.fit_transform(df["keys1"])

In [6]:
temp

array([0, 3, 4, 2, 1])

In [12]:
from sklearn.preprocessing import OrdinalEncoder
encoder = OrdinalEncoder(categories=[["first","sec","thr","four","five"]])

In [13]:
encoder.fit_transform(df[["keys1"]])

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [14]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
arrr = one.fit_transform(df[["keys1"]])

In [19]:
arrr.toarray()

array([[1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [21]:
one.get_feature_names_out()

array(['keys1_first', 'keys1_five', 'keys1_four', 'keys1_sec',
       'keys1_thr'], dtype=object)

In [ ]:
so we get an sparse metrix in case of one hot encoding.
so when we have small number of category we use label encoding or ordinal encoding as per neede.

### Q4. Suppose you have a dataset containing categorical data with 5 unique values. Which encoding technique would you use to transform this data into a format suitable for machine learning algorithms? Explain why you made this choice.

In [ ]:
i used to perform One Hot Encoding(OHE) 

if we have five unique value in a categorical feature. as the number unique value is  only 5 we can easlyy go with 
one hot encoding,it create 5 more feature but it is ok because we get better performance, we get data which is used in ml.

### Q5. In a machine learning project, you have a dataset with 1000 rows and 5 columns. Two of the columns are categorical, and the remaining three columns are numerical. If you were to use nominal encoding to transform the categorical data, how many new columns would be created? Show your calculations.

In [ ]:
we have ttal 5 columns, outof 5 3 is numeric so we have 2 categorical feature.
so number of new feature that may be created is according to the unique value in this 2 categorical feature.

in the below example we have two categorical feature which have 3 3 unique value so then 6 new columns or feature are 
created.

In [20]:
df = pd.DataFrame({
    "cat1" : ["guj","hindi","eng","hindi","eng"],
    "cat2" : ["garba","disco","hip-hop","disco","hip-hop"],
    "num1" : [1,2,3,4,5],
    "num2" : [3,4,5,6,7],
    "num3" : [1,4,7,9,0]    
})
df

cat1     cat2  num1  num2  num3
0    guj    garba     1     3     1
1  hindi    disco     2     4     4
2    eng  hip-hop     3     5     7
3  hindi    disco     4     6     9
4    eng  hip-hop     5     7     0

In [21]:
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()

In [23]:
arr = one.fit_transform(df[["cat1","cat2"]])
arr

<5x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [24]:
new_df = pd.concat([df,pd.DataFrame(arr.toarray(),columns=one.get_feature_names_out())],axis=1)
new_df

cat1     cat2  num1  num2  num3  cat1_eng  cat1_guj  cat1_hindi  \
0    guj    garba     1     3     1       0.0       1.0         0.0   
1  hindi    disco     2     4     4       0.0       0.0         1.0   
2    eng  hip-hop     3     5     7       1.0       0.0         0.0   
3  hindi    disco     4     6     9       0.0       0.0         1.0   
4    eng  hip-hop     5     7     0       1.0       0.0         0.0   

   cat2_disco  cat2_garba  cat2_hip-hop  
0         0.0         1.0           0.0  
1         1.0         0.0           0.0  
2         0.0         0.0           1.0  
3         1.0         0.0           0.0  
4         0.0         0.0           1.0

### Q6. You are working with a dataset containing information about different types of animals, including their  species, habitat, and diet. Which encoding technique would you use to transform the categorical data into a format suitable for machine learning algorithms? Justify your answer.

In [ ]:
so we have data like species, habit, diet so first i cheack what number of unique feature is there in each columns.
if the unique values per columns are not that much so l can use nominal encoding in this senario species are colmns 
which can have lots of diff value so in that case i can use one hot encoding. in diet caolumns we can use label encoding
because diet can be same for lots of animal so there will be a less number of diff value of there will be a less number of
unique value thats why i use label encoding over One hot encoding. And the remaning columns habit can be depend on species 
so think it is batter to use one hot encoding. after then we can pass data for model traning  

### Q7.You are working on a project that involves predicting customer churn for a telecommunications company. You have a dataset with 5 features, including the customers gender, age, contract type, monthly charges, and tenure. Which encoding technique(s) would you use to transform the categorical data into numerical data? Provide a step-by-step explanation of how you would implement the encoding.

In [22]:
data = {
    "gender":["male","female","male","female","male"],
    "age" : [19,18,19,20,22],
    "contract_type" : ["prepaid","postpaid","postpaid","prepaid","prepaid"],
    "monthly charge":[190,180,180,190,190],
    "tenure" : ["yes","no","yes","no","yes"]
}

In [23]:
import pandas as pd
df = pd.DataFrame(data)

In [24]:
df

gender  age contract_type  monthly charge tenure
0    male   19       prepaid             190    yes
1  female   18      postpaid             180     no
2    male   19      postpaid             180    yes
3  female   20       prepaid             190     no
4    male   22       prepaid             190    yes

In [29]:
df

gender  age contract_type  monthly charge tenure
0    male   19       prepaid             190    yes
1  female   18      postpaid             180     no
2    male   19      postpaid             180    yes
3  female   20       prepaid             190     no
4    male   22       prepaid             190    yes

In [25]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [34]:
df["gender"]=encoder.fit_transform(df["gender"])

In [35]:
df

gender  age contract_type  monthly charge tenure
0       1   19       prepaid             190    yes
1       0   18      postpaid             180     no
2       1   19      postpaid             180    yes
3       0   20       prepaid             190     no
4       1   22       prepaid             190    yes

In [36]:
df["contract_type"] = encoder.fit_transform(df[["contract_type"]])

C:\Users\dhruv\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [37]:
df["tenure"]=encoder.fit_transform(df["tenure"])

In [38]:
df

gender  age  contract_type  monthly charge  tenure
0       1   19              1             190       1
1       0   18              0             180       0
2       1   19              0             180       1
3       0   20              1             190       0
4       1   22              1             190       1

In [ ]:
we use label encoding to encode the data.