In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns

## Q1. What is Min-Max scaling, and how is it used in data preprocessing? Provide an example to illustrate its application.

In [ ]:
Min-max scaling it take numeric feature as input and change its scaling. it make each element lie between zero to one.

if we have large amounts in our data set so it take more time to computing any opration, so it take more time to create model.
to redure its computation time we scale numeric feature so then our computation is fast, if our computation is fast then
it create the model fast as compare to precious unscale data. this is a reason why we use scaling.
Min-Max scaling, also known as feature scaling or normalization, is a common data preprocessing technique used in 
machine learning and data analysis to transform numerical features into a standardized range. The goal of Min-Max scaling 
is to rescale the data to a fixed range, typically between 0 and 1, making the data comparable and ensuring that no single 
feature dominates the learning process.

In [4]:
## EX:
df = sns.load_dataset("tips")

In [5]:
df

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [6]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [7]:
t = scaler.fit_transform(df[["tip"]])

In [55]:
new_tip = pd.concat([df,pd.DataFrame(t,columns=["new_tip"])],axis=1)

In [56]:
new_tip

total_bill   tip     sex smoker   day    time  size   new_tip
0         16.99  1.01  Female     No   Sun  Dinner     2  0.001111
1         10.34  1.66    Male     No   Sun  Dinner     3  0.073333
2         21.01  3.50    Male     No   Sun  Dinner     3  0.277778
3         23.68  3.31    Male     No   Sun  Dinner     2  0.256667
4         24.59  3.61  Female     No   Sun  Dinner     4  0.290000
..          ...   ...     ...    ...   ...     ...   ...       ...
239       29.03  5.92    Male     No   Sat  Dinner     3  0.546667
240       27.18  2.00  Female    Yes   Sat  Dinner     2  0.111111
241       22.67  2.00    Male    Yes   Sat  Dinner     2  0.111111
242       17.82  1.75    Male     No   Sat  Dinner     2  0.083333
243       18.78  3.00  Female     No  Thur  Dinner     2  0.222222

[244 rows x 8 columns]

## Q2. What is the Unit Vector technique in feature scaling, and how does it differ from Min-Max scaling? Provide an example to illustrate its application.

In [ ]:
The Unit Vector technique, also known as vector normalization or unit normalization, is another data preprocessing technique
used in feature scaling. Unlike Min-Max scaling or Standardization, which scale the features to a fixed range or zero mean 
with unit variance, the Unit Vector technique scales each feature to have a magnitude of 1. This means that the transformed 
data points lie on the surface of a unit sphere.

Unit Vector technique differs from Min-Max scaling:
    Scaling range:
        In Min-Max scaling, the data is transformed to a fixed range (e.g., [0, 1]) based on the minimum and maximum values of
        the feature in the dataset. On the other hand, the Unit Vector technique scales the data to have a magnitude of 1, 
        effectively transforming it to lie on a unit sphere.

    Effect on distribution: Min-Max scaling and Standardization both preserve the original distribution of the data but place 
        it within a different scale. The Unit Vector technique, on the other hand, does not preserve the original distribution 
        but ensures that each data point has a magnitude of 1.

    Feature-wise scaling: Min-Max scaling and Standardization scale each feature independently. However, the Unit Vector 
        technique scales each data point (or feature vector) based on its magnitude, making it more suitable for cases where
        the relationships between features are important, such as in some geometric or distance-based algorithms.

        
In some machine learning algorithms like K-nearest neighbors (KNN), cosine similarity, and dot product-based algorithms,
feature vectors with unit magnitude are desirable as they emphasize direction rather than the magnitude itself.

Overall, the Unit Vector technique is a useful feature scaling method when the direction of the feature vectors is more 
relevant than their magnitude and when dealing with algorithms that are sensitive to the scale of features but not their 
distribution.

In [2]:
from sklearn.preprocessing import normalize 

In [3]:
df = sns.load_dataset("taxis")

In [4]:
df = df[["passengers","distance","fare","tip","tolls","total"]]
df

passengers  distance  fare   tip  tolls  total
0              1      1.60   7.0  2.15    0.0  12.95
1              1      0.79   5.0  0.00    0.0   9.30
2              1      1.37   7.5  2.36    0.0  14.16
3              1      7.70  27.0  6.15    0.0  36.95
4              3      2.16   9.0  1.10    0.0  13.40
...          ...       ...   ...   ...    ...    ...
6428           1      0.75   4.5  1.06    0.0   6.36
6429           1     18.74  58.0  0.00    0.0  58.80
6430           1      4.14  16.0  0.00    0.0  17.30
6431           1      1.12   6.0  0.00    0.0   6.80
6432           1      3.85  15.0  3.36    0.0  20.16

[6433 rows x 6 columns]

In [6]:
data_new  =pd.concat([pd.DataFrame(normalize(df[["fare","passengers","distance","tip"]]),columns=["fare","passengers","distance","tip"]),df], axis=1)

In [7]:
data_new

fare  passengers  distance       tip  passengers  distance  fare  \
0     0.925692    0.132242  0.211587  0.284320           1      1.60   7.0   
1     0.969020    0.193804  0.153105  0.000000           1      0.79   5.0   
2     0.932440    0.124325  0.170326  0.293408           1      1.37   7.5   
3     0.938818    0.034771  0.267737  0.213842           1      7.70  27.0   
4     0.919154    0.306385  0.220597  0.112341           3      2.16   9.0   
...        ...         ...       ...       ...         ...       ...   ...   
6428  0.939621    0.208805  0.156604  0.221333           1      0.75   4.5   
6429  0.951435    0.016404  0.307412  0.000000           1     18.74  58.0   
6430  0.966349    0.060397  0.250043  0.000000           1      4.14  16.0   
6431  0.970087    0.161681  0.181083  0.000000           1      1.12   6.0   
6432  0.944701    0.062980  0.242473  0.211613           1      3.85  15.0   

       tip  tolls  total  
0     2.15    0.0  12.95  
1     0.00    0.0   9.30  
2     2.36    0.0  14.16  
3     6.15    0.0  36.95  
4     1.10    0.0  13.40  
...    ...    ...    ...  
6428  1.06    0.0   6.36  
6429  0.00    0.0  58.80  
6430  0.00    0.0  17.30  
6431  0.00    0.0   6.80  
6432  3.36    0.0  20.16  

[6433 rows x 10 columns]

## Q3. What is PCA (Principle Component Analysis), and how is it used in dimensionality reduction? Provide an example to illustrate its application.

In [ ]:
Principal Component Analysis is a technique of feature extraction that maps a higher dimensional feature space to a 
lower-dimensional feature space. While reducing the number of dimensions, PCA ensures that maximum information of the 
original dataset is retained in the dataset with the reduced no. of dimensions and the co-relation between the newly 
obtained Principal Components is minimum. The new features obtained after applying PCA are called Principal Components
and are denoted as PCi (i=1,2,3…n). 


In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 

In [7]:
df = pd.DataFrame({
    "reading_hours" : [3,4,6,7,9,5,4,3],
    "other_activity_time" : [5,4,3,2,1,2,3,4]
})

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x = scaler.fit_transform(df)
x

array([[-1.0816841 ,  1.63299316],
       [-0.57265629,  0.81649658],
       [ 0.44539933,  0.        ],
       [ 0.95442714, -0.81649658],
       [ 1.97248277, -1.63299316],
       [-0.06362848, -0.81649658],
       [-0.57265629,  0.        ],
       [-1.0816841 ,  0.81649658]])

In [14]:
df[["reading_hours" , "other_activity_time"]] = x


In [15]:
df

reading_hours  other_activity_time
0      -1.081684             1.632993
1      -0.572656             0.816497
2       0.445399             0.000000
3       0.954427            -0.816497
4       1.972483            -1.632993
5      -0.063628            -0.816497
6      -0.572656             0.000000
7      -1.081684             0.816497

In [16]:
from sklearn.decomposition import PCA
pca = PCA(n_components = 1)

In [17]:
pca_data  = pca.fit_transform(df)

In [18]:
pca_data

array([[-1.9195667 ],
       [-0.98227941],
       [ 0.31494489],
       [ 1.25223218],
       [ 2.54945648],
       [ 0.53235814],
       [-0.40492914],
       [-1.34221643]])

In [19]:
pca.explained_variance_

array([2.15221871])

In [20]:
pca.explained_variance_ratio_

array([0.94159568])

In [ ]:
## we get 94 variance 
# we are able to create line which contain 94 % variance 

## Q4. What is the relationship between PCA and Feature Extraction, and how can PCA be used for Feature Extraction? Provide an example to illustrate this concept.

In [ ]:
PCA (Principal Component Analysis) is a technique commonly used for feature extraction in data analysis and machine learning.
Feature extraction involves transforming the original set of features into a new set of features that captures the most 
important information in the data while reducing its dimensionality. PCA is a specific method of feature extraction that 
aims to transform the data into a new coordinate system defined by the principal components, which are linear combinations of
the original features.

The relationship between PCA and feature extraction lies in the fact that PCA is a method of extracting new features 
(principal components) from the original data. These principal components are orthogonal to each other and capture the 
directions of maximum variance in the data. By selecting a subset of the principal components, you can effectively create
a reduced-dimensional representation of the data while preserving the most important patterns and minimizing the impact 
of noise.

In [5]:
data = {
    "number_of_room" : [2,3,4,5,6],
    "size" : [200,300,350,400,450]
}

In [6]:
import pandas as pd
df = pd.DataFrame(data)
df

number_of_room  size
0               2   200
1               3   300
2               4   350
3               5   400
4               6   450

In [2]:
from sklearn.decomposition import PCA

In [3]:
pca = PCA(n_components=1) 

In [7]:
pca.fit_transform(df)

array([[ 140.01402417],
       [  40.01095585],
       [  -9.99868541],
       [ -60.00832667],
       [-110.01796793]])

In [9]:
pca.explained_variance_ratio_

array([0.9999927])

In [ ]:
## so from two feature now we have one feature 
## 2D --> 1D.


## Q5. You are working on a project to build a recommendation system for a food delivery service. The dataset contains features such as price, rating, and delivery time. Explain how you would use Min-Max scaling to preprocess the data.

In [ ]:
# we suppose that we have all the training data.
we can assume we have three feature:
    1. price : price can be in k like 500 ,1000,5500,...
    2. rating : rating can be in 0 to 5 
    3. delivery time : delivery time can be in day like 1,2,3,4,5,6 

Min-Max scaling will transform these features to a common range, making them comparable and preventing any one
feature from dominating the recommendation process.
        
Scaling the features appropriately ensures that the recommendations are not biased towards any specific feature with 
a larger range or magnitude.

as we know any feature can not have value < 0 and all the feature have the value which are different and there is not a order
,so we can use min-max scaling like this :

In [22]:
df = pd.DataFrame({
    "price":[500,200,1000,2000,1500,900,1200],
    "rating":[3,2,4,4,5,3,5],
    "delivery_time":[2,3,1,4,2,3,3]
})

In [23]:
df

price  rating  delivery_time
0    500       3              2
1    200       2              3
2   1000       4              1
3   2000       4              4
4   1500       5              2
5    900       3              3
6   1200       5              3

In [24]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [25]:
sl = scaler.fit_transform(df[["rating","delivery_time"]])

In [26]:
new = pd.DataFrame(sl,columns=["new_rating","new_time"])

In [27]:
all_new = pd.concat([df,new] , axis=1)
all_new

price  rating  delivery_time  new_rating  new_time
0    500       3              2    0.333333  0.333333
1    200       2              3    0.000000  0.666667
2   1000       4              1    0.666667  0.000000
3   2000       4              4    0.666667  1.000000
4   1500       5              2    1.000000  0.333333
5    900       3              3    0.333333  0.666667
6   1200       5              3    1.000000  0.666667

## Q6. You are working on a project to build a model to predict stock prices. The dataset contains many features, such as company financial data and market trends. Explain how you would use PCA to reduce the dimensionality of the dataset.

In [ ]:
first of all 
-clean the data 
-scale the data
-now we can apply the pca
first of all we take care the variance that is capture by our pca
we start with pca =1 
and check if it contain 85 or aboue % of data variance
than we stop other wise 
we go for pca = 2 
pca = 3
pca = 4
like wise .
when we get pca which contain 85% or above data variance then we stop and we can say that now this data can use for our further
process

## Q7. For a dataset containing the following values: [1, 5, 10, 15, 20], perform Min-Max scaling to transform the values to a range of -1 to 1.

In [16]:
from sklearn.preprocessing import MinMaxScaler

df1 = pd.DataFrame({"value" :[1, 5, 10, 15, 20]})
df1

value
0      1
1      5
2     10
3     15
4     20

In [17]:
scaler = MinMaxScaler(feature_range=(-1,1))

In [18]:
scaler.fit(df1[["value"]])

MinMaxScaler(feature_range=(-1, 1))

In [19]:
value_new = scaler.transform(df1[["value"]])

In [20]:
df2 = pd.DataFrame(value_new, columns=["value"])

In [21]:
df2

value
0 -1.000000
1 -0.578947
2 -0.052632
3  0.473684
4  1.000000

## Q8. For a dataset containing the following features: [height, weight, age, gender, blood pressure], perform Feature Extraction using PCA. How many principal components would you choose to retain, and why?

In [3]:
import pandas as pd
data = pd.DataFrame({
    "height" : [5,6,4,5,6,5],
    "weight" : [60,50,66,70,80,78],
    "age" : [18,20,30,25,15,22],
    "gender" : ["m","f","m","f","f","m"],
    "blood_pressure" : [190,160,90,67,89,140]
})

In [4]:
data

height  weight  age gender  blood_pressure
0       5      60   18      m             190
1       6      50   20      f             160
2       4      66   30      m              90
3       5      70   25      f              67
4       6      80   15      f              89
5       5      78   22      m             140

In [5]:
from sklearn.preprocessing import LabelEncoder
label = LabelEncoder()

data["gender"] = label.fit_transform(data["gender"])
data

height  weight  age  gender  blood_pressure
0       5      60   18       1             190
1       6      50   20       0             160
2       4      66   30       1              90
3       5      70   25       0              67
4       6      80   15       0              89
5       5      78   22       1             140

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [7]:
data[["height","weight","age","gender","blood_pressure"]] = scaler.fit_transform(data[["height","weight","age","gender","blood_pressure"]])


In [8]:
data

height    weight       age  gender  blood_pressure
0 -0.242536 -0.711531 -0.755483     1.0        1.536177
1  1.212678 -1.681800 -0.343401    -1.0        0.851742
2 -1.697749 -0.129369  1.717007     1.0       -0.745274
3 -0.242536  0.258738  0.686803    -1.0       -1.270008
4  1.212678  1.229008 -1.373606    -1.0       -0.768089
5 -0.242536  1.034954  0.068680     1.0        0.395452

In [9]:
from sklearn.decomposition import PCA
pca = PCA(n_components=1)

In [10]:
pca_data = pca.fit_transform(data)

In [11]:
data

height    weight       age  gender  blood_pressure
0 -0.242536 -0.711531 -0.755483     1.0        1.536177
1  1.212678 -1.681800 -0.343401    -1.0        0.851742
2 -1.697749 -0.129369  1.717007     1.0       -0.745274
3 -0.242536  0.258738  0.686803    -1.0       -1.270008
4  1.212678  1.229008 -1.373606    -1.0       -0.768089
5 -0.242536  1.034954  0.068680     1.0        0.395452

In [12]:
pca_data

array([[-0.18098956],
       [-1.75868613],
       [ 2.66669348],
       [ 0.36084706],
       [-1.76565308],
       [ 0.67778823]])

In [16]:
pca.explained_variance_ratio_

array([0.46480422])

In [17]:
pca.explained_variance_ratio_.cumsum()[0]

0.4648042162845623

In [43]:
## variance is not > 0.85 or(85%)

In [18]:
for i in range(1,len(data.columns)+1):
    pca = PCA(n_components = i )
    
    pca_data = pca.fit_transform(data)
    
    if (pca.explained_variance_ratio_.cumsum()[-1]) > 0.85:
        print(i)
        break
    

3


In [19]:
pca_data

array([[-0.18098956,  1.99041211, -0.63208694],
       [-1.75868613,  1.05052791,  1.37883658],
       [ 2.66669348, -0.07277784,  0.51450254],
       [ 0.36084706, -1.51332094,  0.87028391],
       [-1.76565308, -1.61003276, -0.84684241],
       [ 0.67778823,  0.15519153, -1.28469367]])

In [20]:
pca.explained_variance_ratio_.cumsum()

array([0.46480422, 0.79737342, 0.98705379])

In [60]:
## so we take 3 principla component to retain our data

In [61]:
## now we take this data as our train data and train the model